name: foreign_data
source:
  type: mysql
  connection:
    host: localhost
    port: 3306
    database: BIRD
    user: root
    password: xuhongming3410
  table: foreign_data
description: 'BIRD database table: foreign_data'
