name: major
source:
  type: mysql
  connection:
    host: localhost
    port: 3306
    database: BIRD
    user: root
    password: xuhongming3410
  table: major
description: 'BIRD database table: major'
