name: posthistory
source:
  type: mysql
  connection:
    host: localhost
    port: 3306
    database: BIRD
    user: root
    password: xuhongming3410
  table: posthistory
description: 'BIRD database table: posthistory'
