name: seasons
source:
  type: mysql
  connection:
    host: localhost
    port: 3306
    database: BIRD
    user: root
    password: xuhongming3410
  table: seasons
description: 'BIRD database table: seasons'
