name: hero_power
source:
  type: mysql
  connection:
    host: localhost
    port: 3306
    database: BIRD
    user: root
    password: xuhongming3410
  table: hero_power
description: 'BIRD database table: hero_power'
